spring:
  application:
    name: foodly-backend
  datasource:
    url: jdbc:mysql://localhost:3306/foodly
    username: "Alvinqw12"
    password: "@Alvin2003"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 3080
  servlet:
    context-path: /api
